# Generated by Django 5.1 on 2024-09-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dName', models.CharField(max_length=100)),
                ('Loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.PositiveIntegerField()),
                ('eName', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('MGR', models.IntegerField()),
                ('hireDate', models.DateField()),
                ('salary', models.IntegerField()),
                ('comm', models.IntegerField()),
                ('deptNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
