# Generated by Django 5.1 on 2024-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='MGR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='comm',
            field=models.DecimalField(decimal_places=5, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='salary',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
    ]
